; =========================================
; 全局公共配置（两块板子都适用的基础设定）
; =========================================
[env]
platform = espressif32
framework = arduino
monitor_speed = 115200  ; 串口打印波特率（标准速度）
upload_speed = 921600   ; 烧录速度拉满，节约你的生命！

; =========================================
; 环境一：你的 "眼睛" (ESP32-CAM)
; =========================================
[env:esp32cam]
board = esp32cam
; 【极其核心】强制开启外部 PSRAM 内存支持，否则摄像头一拍照就内存溢出死机
build_flags =
    -DBOARD_HAS_PSRAM
    -mfix-esp32-psram-cache-issue

monitor_rts = 0
monitor_dtr = 0